server:
  port: 8221
logging:
  level:
    root: INFO
    com.ch.cb_user.mapper: debug
    org.springframework.web: debug
    io.swagger.models.parameters.AbstractSerializableParameter: error
eureka:
  instance:
    hostname: localhost
    port: 8200
swagger:
  enable: true
  rpc-package-scan: true
spring:
  datasource:
    user:
      jdbc-url: jdbc:mysql://rm-2ze48v5j1x8f6f400.mysql.rds.aliyuncs.com:3306/cb_user?useUnicode=true&characterEncoding=utf-8&autoReconnect=true&useSSL=false
      username: lch
      password: aA657597915
      driver-class-name: com.mysql.jdbc.Driver
      # 使用druid数据源
      type: com.alibaba.druid.pool.DruidDataSource
