spring:
  application:
    name: @pom.artifactId@
  profiles:
    #安全管理开始
    active: @env@
  security:
    user:
      name: "admin"
      password: "admin"

logging:
  config: classpath:logback/logback-${spring.profiles.active}.xml