spring:
  application:
    name: @pom.artifactId@
  profiles:
    #安全管理开始
    active: @env@
  security:
    user:
      name: "admin"
      password: "admin"
  management:
    endpoints:
      web:
        exposure:
          include: "*"
    endpoint:
      health:
        show-details: ALWAYS
logging:
  config: classpath:logback/logback-${spring.profiles.active}.xml