#运行的端口号
server:
  port: 8200
#logback配置，开发模式日志级别为 INFO
logging:
  level:
    root: INFO
    org.springframework.web: info
spring:
  # 注册到Admin
  boot:
    admin:
      client:
        url: http://123.56.81.29:8202
# 注册中心配置开始
eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${spring.security.user.name}:${spring.security.user.password}@${eureka.instance.hostname}:${server.port}/eureka/
  server:
    useReadOnlyResponseCache: false
    waitTimeInMsWhenSyncEmpty: 0
    #    自我保护模式，当出现出现网络分区、eureka在短时间内丢失过多客户端时，会进入自我保护模式，即一个服务长时间没有发送心跳，eureka  也不会将其删除，默认为true
    enableSelfPreservation: false
    #eureka server清理无效节点的时间间隔，默认60000毫秒，即60秒
    evictionIntervalTimerInMs: 5000
    peerNodeReadTimeoutMs: 2000
    # 每隔X秒钟就把响应给客户端的实例列表更新一次，设置为0时无法启动
    responseCacheUpdateIntervalMs: 30000
    # 注册中心配置结束