spring:
  application:
    name: @pom.artifactId@
  profiles:
    active: @env@
  security:
    user:
      name: "admin"
      password: "admin"
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
  management:
    security:
      enabled: false
#    endpoints:
#      web:
#        exposure:
#          include: "*"
#    endpoint:
#      health:
#        show-details: ALWAYS
logging:
  config: classpath:logback/logback-${spring.profiles.active}.xml

path:
  exclude:
    - /userService/api/ext
