server:
  port: 8201
logging:
  level:
    root: INFO
    org.springframework.web: info
eureka:
  instance:
    hostname: localhost
    port: 8200
spring:
  # 注册到Admin
  boot:
    admin:
      client:
        url: http://localhost:8202
  #redis
#  redis:
#    host: 123.57.186.182
#    port: 3187
#    timeout: 3000ms
#    database: 1
#    password: jkhh120HlwQAZ
#    jedis:
#      pool:
#        max-active: 8
#        max-idle: 8
#        min-idle: 0
#        max-wait: -1ms



